project_id: 7k0yj6e1h3c7dcwo
version: "{build}"

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 0.10.28

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g grunt-cli
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - ps: npm test # PowerShell
  - cmd: npm test
